### ISSUE TITLE
Issue with the tracker

### ISSUE THREAD

**Issue by imdeepmind** [JeffreyGbeho/leetcode-tracker#1]
Seems like there is some issue with the tracker. I solved one hard question on LeetCode however in the extension, the tracker is counting it as easy question.

Have a look at the screenshot. I solved one easy and one hard question. Still the tracker is showing as 2 easy questions.

![Screenshot from 2024-02-01 20-53-57](https://github.com/JeffreyGbeho/leetcode-tracker/assets/34741145/e8cd00e5-8570-4e58-99e6-7913ebb1264a)

Note: This is the hard question that I solved - https://leetcode.com/problems/text-justification/

**Comment by satyamdeb12** [comment]
If the submitted answer is wrong and then I resubmit the latest code, the latest submitted code is not committed into my repo. The lines of code are jumbled when committed into my repo.
