### ISSUE TITLE
A new folder is created but solution is not added.

### ISSUE THREAD

**Issue by ChaitanyaYeole02** [JeffreyGbeho/leetcode-tracker#3]
When I click on Submit button, my github repo has a new folder inside that folder is Readme.md and .py file. But my .py file is empty.

**Comment by ChaitanyaYeole02** [comment]
New leetcode used monaco editor, you need to use monaco editor check to get the code.

```
if (window.monaco && monaco.editor) {
  const models = monaco.editor.getModels();
  
  if (models.length > 0) {
    const code = models[0].getValue();
    console.log("Retrieved Code from Monaco Model:\n", code);
  } else {
    console.log("No models found in Monaco Editor.");
  }
} else {
  console.log("Monaco Editor is not accessible.");
}
```

This should give you the code.

**Comment by ChaitanyaYeole02** [comment]
Hey, is this resolved, as I can still see the same issue for Python submissions.

**Comment by JeffreyGbeho** [comment]
I tested it this morning and the python problem submission worked well for me. Could you provide more details about the error message, the leetcode problem you were trying to solve please ?

**Comment by ChaitanyaYeole02** [comment]
The python problems are submitted but the .py file is empty. Today I did the Daily Problem and clicked on Submitted, it pushed the folder and inside the folder there were two files .py and .md. `.md` file had the problem and `.py` file did not have any solution.
https://github.com/ChaitanyaYeole02/leetcode-solutions/tree/main/1829-MaximumXORforEachQuery

**Comment by JeffreyGbeho** [comment]
I think I managed to reproduce the bug. You're trying to solve the problem with Python3 and not Python, right?
Because Python works fine but with Python3 I get the same issue as you

**Comment by ChaitanyaYeole02** [comment]
I think leetcode is using Monaco editor and for Python3 it works a bit differently, the logic would be different for Python3.

**Comment by JeffreyGbeho** [comment]
I fixed the issue and sent the new package. Now we have to wait a few days for Google to analyze the extension. If all is good, your extension will be updated automatically.
If you'd like, I can let you know when I hear back from Google so you can test it again

**Comment by ChaitanyaYeole02** [comment]
Yes, please let me know.

**Comment by JeffreyGbeho** [comment]
The extension has been updated. Could you test it please and let me know if everything works well ?
